spring.application.name=Employment-App

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/Employment_App
spring.datasource.username=root
spring.datasource.password=Cassi8rex
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Logging Configuration
logging.level.com.foundationalsystems.mohealthnet=DEBUG
logging.level.org.springframework.security=DEBUG

# Server Configuration
server.port=8080
