<<<<<<< Updated upstream
spring.application.name=Employment-App

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/Employment_App
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Logging Configuration
logging.level.com.foundationalsystems.mohealthnet=DEBUG
logging.level.org.springframework.security=DEBUG

# Server Configuration
server.port=8080
=======
spring.application.name=mohealthnet

# Server Configuration
server.port=8080
server.servlet.context-path=/

# Logging
logging.level.root=INFO
logging.level.com.foundationalsystems.mohealthnet=DEBUG

# Database Configuration (when enabled)
spring.datasource.url=jdbc:mysql://localhost:3306/employment_app
spring.datasource.username=root
spring.datasource.password=Beeta70@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.ImprovedNamingStrategy
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
>>>>>>> Stashed changes
